trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
resources:
  repositories:
  - repository: backend
    type: github
    endpoint: folkehelseinstituttet (2)
    name: folkehelseinstituttet/Fhi.Koronasertifikat.Verifikasjon.Backend
    ref: main

variables: 
- template: Pipeline/version-number.yml@backend
- name: versionRev
  value: $[counter(variables['version'], 1)]
- name: finalVersion
  value: $(version)-data-rev.$(versionRev)
- name: azureConnection
  value: FHI-Koronasertifikat.Verifisering-ARM-Test
  
extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Test
    azureConnection: ${{ variables.azureConnection }}
    appVersion: $(finalVersion)
    doRelease: 'true'
    environment: 'test'
