trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
resources:
  repositories:
  - repository: backend
    type: github
    endpoint: folkehelseinstituttet (2)
    name: folkehelseinstituttet/Fhi.Koronasertifikat.Verifikasjon.Backend
    ref: main

variables:
- template: Pipeline/version-number.yml@backend
- name: versionRev
  value: $[counter(variables['version'], 1)]
- name: finalVersion
  value: $(version)-data-rc.$(versionRev)

extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-QA
    appVersion: $(finalVersion)
    doRelease: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
    environment: 'preprod'
