trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'

resources:
  repositories:
  - repository: backend
    type: github
    endpoint: folkehelseinstituttet (2)
    name: folkehelseinstituttet/Fhi.Koronasertifikat.Verifikasjon.Backend
    ref: main

variables: 
- template: Pipeline/version-number.yml@backend
- name: finalVersion
  value: $(version)-data
  
extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Prod
    appVersion: $(finalVersion)
    doRelease: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    environment: 'prod'
